version: '3.8'

services:
  web:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "6000:5000"  # Maps the container's port 5000 to the host's port 6000
    environment:
      - FLASK_APP=core/server.py  
    volumes:
      - .:/app 
    command: flask run --host=0.0.0.0  # Ensures Flask runs accessible on all IPs
