"""Upgrade

Revision ID: 2b76e386a6b1
Revises: 52a401750a76
Create Date: 2024-09-04 18:50:54.126007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b76e386a6b1'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('assignments', 'state',
    #            existing_type=sa.VARCHAR(length=9),
    #            nullable=False)
    # op.alter_column('teachers', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # # ### end Alembic commands ###
    pass


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('teachers', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('assignments', 'state',
    #            existing_type=sa.VARCHAR(length=9),
    #            nullable=True)
    # # ### end Alembic commands ###
    pass
